
2020-04-08 07:52:53 --- CRITICAL: View_Exception [ 0 ]: The requested view Usuario\apagar could not be found ~ SYSPATH\classes\Kohana\View.php [ 265 ] in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 07:52:53 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php(145): Kohana_View->set_filename('Usuario\\apagar')
#1 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(58): Kohana_View->__construct('Usuario\\apagar')
#2 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(92): Controller_Layout->init_action_template()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(69): Controller_Layout->before()
#4 [internal function]: Kohana_Controller->execute()
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#6 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#8 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#9 {main} in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 07:52:56 --- CRITICAL: View_Exception [ 0 ]: The requested view Usuario\visualizar could not be found ~ SYSPATH\classes\Kohana\View.php [ 265 ] in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 07:52:56 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php(145): Kohana_View->set_filename('Usuario\\visuali...')
#1 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(58): Kohana_View->__construct('Usuario\\visuali...')
#2 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(92): Controller_Layout->init_action_template()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(69): Controller_Layout->before()
#4 [internal function]: Kohana_Controller->execute()
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#6 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#8 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#9 {main} in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 07:53:00 --- CRITICAL: View_Exception [ 0 ]: The requested view Usuario\atualizar could not be found ~ SYSPATH\classes\Kohana\View.php [ 265 ] in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 07:53:00 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php(145): Kohana_View->set_filename('Usuario\\atualiz...')
#1 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(58): Kohana_View->__construct('Usuario\\atualiz...')
#2 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(92): Controller_Layout->init_action_template()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(69): Controller_Layout->before()
#4 [internal function]: Kohana_Controller->execute()
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#6 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#8 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#9 {main} in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 10:03:20 --- CRITICAL: View_Exception [ 0 ]: The requested view Usuario\Clientes could not be found ~ SYSPATH\classes\Kohana\View.php [ 265 ] in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 10:03:20 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php(145): Kohana_View->set_filename('Usuario\\Cliente...')
#1 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(58): Kohana_View->__construct('Usuario\\Cliente...')
#2 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(92): Controller_Layout->init_action_template()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(69): Controller_Layout->before()
#4 [internal function]: Kohana_Controller->execute()
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#6 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#8 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#9 {main} in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 10:04:47 --- CRITICAL: View_Exception [ 0 ]: The requested view Usuario\remover could not be found ~ SYSPATH\classes\Kohana\View.php [ 265 ] in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 10:04:47 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php(145): Kohana_View->set_filename('Usuario\\remover')
#1 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(58): Kohana_View->__construct('Usuario\\remover')
#2 D:\xampp\htdocs\aditum.local\application\classes\Controller\Layout.php(92): Controller_Layout->init_action_template()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(69): Controller_Layout->before()
#4 [internal function]: Kohana_Controller->execute()
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#6 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#8 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#9 {main} in D:\xampp\htdocs\aditum.local\system\classes\Kohana\View.php:145
2020-04-08 10:16:48 --- CRITICAL: Database_Exception [ 23000 ]: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`aditum`.`usuarios`, CONSTRAINT `fk_usuarios_tipousuarios1` FOREIGN KEY (`tipousuario_id`) REFERENCES `tipousuarios` (`id`) ON DELETE CASCADE) [ INSERT INTO usuarios (email, nomeusuario, senha) VALUES ('eide.lacera@gmail.com', 'eideei', 'edsl1489') ] ~ MODPATH\database\classes\Kohana\Database\PDO.php [ 157 ] in D:\xampp\htdocs\aditum.local\modules\database\classes\Kohana\Database\Query.php:251
2020-04-08 10:16:48 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\modules\database\classes\Kohana\Database\Query.php(251): Kohana_Database_PDO->query(2, 'INSERT INTO usu...', false, Array)
#1 D:\xampp\htdocs\aditum.local\modules\orm\classes\Kohana\ORM.php(1488): Kohana_Database_Query->execute(Object(Database_PDO))
#2 D:\xampp\htdocs\aditum.local\modules\orm\classes\Kohana\ORM.php(1591): Kohana_ORM->create(NULL)
#3 D:\xampp\htdocs\aditum.local\application\classes\Model\Usuario.php(35): Kohana_ORM->save()
#4 D:\xampp\htdocs\aditum.local\application\classes\Controller\Usuario.php(21): Model_Usuario::salvar(Array)
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(84): Controller_Usuario->action_novo()
#6 [internal function]: Kohana_Controller->execute()
#7 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#8 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#9 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#10 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#11 {main} in D:\xampp\htdocs\aditum.local\modules\database\classes\Kohana\Database\Query.php:251
2020-04-08 10:27:07 --- CRITICAL: Error [ 0 ]: Using $this when not in object context ~ APPPATH\classes\Model\TipoUsuario.php [ 75 ] in D:\xampp\htdocs\aditum.local\application\classes\Controller\Usuario.php:20
2020-04-08 10:27:07 --- DEBUG: #0 D:\xampp\htdocs\aditum.local\application\classes\Controller\Usuario.php(20): Model_TipoUsuario::lista()
#1 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Controller.php(84): Controller_Usuario->action_novo()
#2 [internal function]: Kohana_Controller->execute()
#3 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client\Internal.php(94): ReflectionMethod->invoke(Object(Controller_Usuario))
#4 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request\Client.php(114): Kohana_Request_Client_Internal->execute_request(Object(Request), Object(Response))
#5 D:\xampp\htdocs\aditum.local\system\classes\Kohana\Request.php(1000): Kohana_Request_Client->execute(Object(Request))
#6 D:\xampp\htdocs\aditum.local\public\index.php(118): Kohana_Request->execute()
#7 {main} in D:\xampp\htdocs\aditum.local\application\classes\Controller\Usuario.php:20